spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/{dbName}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: { dbUsername }
    password: { dbPassword }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: info
    com.ll.ebook.app: debug
    org.hibernate.type.descriptor.sql: trace